// playground/web/src/pages/hi/[name].vue
<script setup lang="ts">
const router = useRouter()
const route = useRoute('/hi/[name]')
const user = useUserStore()

watchEffect(() => {
  user.setNewName(route.params.name)
})
</script>

<template>
  <div>
    <div>
      Hi, {{ user.savedName }}
    </div>

    <div text-sm op-75>
      Dynamic route!
    </div>

    <div v-if="user.otherNames.length" text-sm mt-4>
      <div op-75>
        aka:
      </div>
      <div v-for="otherName in user.otherNames" :key="otherName">
        <RouterLink :to="`/hi/${otherName}`" replace>
          {{ otherName }}
        </RouterLink>
      </div>
    </div>

    <button text-sm btn m-3 @click="router.back()">
      Back
    </button>

    <TheCounter :initial="user.otherNames.length" />
  </div>
</template>

// playground/react/src/pages/hi/[name].tsx
import { Link } from 'react-router'

function hi() {
  const navigate = useNavigate()
  const { savedName, otherNames, setNewName } = useUserStore()
  const params = useParams()
  useEffect(() => setNewName(params.name!), [params.name])

  return (
    <div>
      <div>
        Hi,
        {savedName}
      </div>

      <div text-sm op-75>
        Dynamic route!
      </div>

      {
        otherNames().length
          ? (
              <div text-sm mt-4>
                <div op-75>
                  aka:
                </div>
                {otherNames().map(otherName => (
                  <div key={otherName}>
                    <Link to={`/hi/${otherName}`} replace>
                      {otherName}
                    </Link>
                  </div>
                ))}
              </div>
            )
          : ''
      }

      <button className="btn" text-sm m-3 onClick={() => navigate(-1)}>
        Back
      </button>

      <TheCounter initial={otherNames().length} />
    </div>
  )
}

export default hi
