// playground/app/src/pages/index.vue
<script setup lang="ts">
const user = useUserStore()
const name = ref(user.savedName)

function go() {
  if (name.value)
    uni.navigateTo({ url: `/pages/hi?name=${encodeURIComponent(name.value)}` })
}
</script>

<template>
  <div>
    <view>
      <Icon icon="carbon:campsite" width="36px" />
    </view>

    <uni-link href="https://github.com/SoulLyoko/vixt" show-under-line="false" color="#333">
      Vixt
    </uni-link>

    <view text-sm op-75>
      Vixt App
    </view>

    <div py-4 />

    <TheInput v-model="name" placeholder="What's your name?" autocomplete="false" @keydown.enter="go" />

    <button text-sm btn m-3 :disabled="!name" @click="go">
      Go
    </button>
  </div>
</template>

<route type="home" lang="yaml">
meta:
  layout: home
</route>

// playground/react/src/pages/index.tsx
/*
route

meta:
  layout: home
*/

function index() {
  const { savedName } = useUserStore()
  const [name, setName] = useState(savedName)
  const navigate = useNavigate()
  const go = () => name && navigate(`/hi/${encodeURIComponent(name)}`)
  return (
    <div>
      <Icon icon="carbon:campsite" width="36px" m-auto />

      <a href="https://github.com/SoulLyoko/vixt" target="_blank">
        Vixt
      </a>

      <div text-sm op-75>
        {ENV.VITE_APP_NAME}
      </div>

      <div py-4></div>

      <TheInput
        value={name}
        placeholder="What's your name?"
        autoComplete="off"
        onChange={e => setName(e)}
        onKeyDown={e => e.key === 'Enter' && go()}
      />

      <div>
        <button className="btn" text-sm m-3 onClick={() => go()}>
          Go
        </button>
      </div>
    </div>
  )
}

export default index
