// playground/layer-vue/src/layouts/shared.vue
<script setup lang="ts">
defineProps<{ name?: string }>()
</script>

<template>
  <main px-4 py-10 text="center gray-700 dark:gray-200">
    <slot>
      <RouterView />
    </slot>
    <TheFooter />
    <div text-center mx-auto mt-5 text-sm opacity-50>[{{ name }} Layout]</div>
  </main>
</template>

// playground/layer-react/src/layouts/shared.tsx
import { Outlet } from 'react-router'

function SharedLayout(props: { name: string }) {
  return (
    <main px-4 py-10 text="center gray-700 dark:gray-200">
      <Outlet />
      <TheFooter />
      <div mt-5 text-sm opacity-50>
        {`[${props.name} Layout]`}
      </div>
    </main>
  )
}

export default SharedLayout
