// playground/layer-react/src/components/TheCounter.tsx
export default function TheCounter(props: { initial: number }) {
  const [count, { inc, dec, reset }] = useCounter(props.initial)
  useEffect(() => reset(), [props.initial])

  return (
    <div>
      <button className="dec btn" text-xs onClick={() => dec()}>
        -
      </button>
      { count }
      <button className="btn inc" text-xs onClick={() => inc()}>
        +
      </button>
    </div>
  )
}

// playground/app/src/components/TheCounter.vue
<script setup lang="ts">
const props = defineProps<{
  initial: number
}>()

const { count, inc, dec } = useCounter(props.initial)
</script>

<template>
  <view>
    <button class="dec" btn text-xs @click="dec()">
      -
    </button>
    {{ count }}
    <button class="inc" btn text-xs @click="inc()">
      +
    </button>

    <view>
      (TheCounter Component has been overridden)
    </view>
  </view>
</template>
