// playground/react/src/components/TheFooter.tsx
import { Link } from 'react-router'

export default function TheFooter() {
  const [isDark, toggleDark] = useDark()
  return (
    <nav flex gap-4 justify-center mt-6 text-xl>
      <Link icon-btn to="/" title="Home">
        <Icon icon="carbon:campsite" />
      </Link>

      <button icon-btn title="ToggleDark" onClick={() => toggleDark()}>
        <Icon icon={isDark ? 'carbon:sun' : 'carbon:moon'} />
      </button>

      <a icon-btn rel="noreferrer" href="https://github.com/SoulLyoko/vixt" target="_blank" title="GitHub">
        <Icon icon="carbon:logo-github" />
      </a>

      <Link icon-btn to="/about" title="About">
        <Icon icon="carbon:dicom-overlay" />
      </Link>
    </nav>
  )
}

// playground/app/src/components/TheFooter.vue
<script setup lang="ts">

</script>

<template>
  <view flex="~ gap-4" justify-center mt-6 text-xl>
    <navigator icon-btn url="/pages/index" title="Home">
      <Icon icon="carbon:campsite" width="20px" />
    </navigator>

    <view icon-btn title="ToggleDark" @click="toggleDark()">
      <Icon :icon="isDark ? 'carbon:sun' : 'carbon:moon'" width="20px" />
    </view>

    <uni-link icon-btn href="https://github.com/SoulLyoko/vixt" title="GitHub">
      <Icon icon="carbon:logo-github" width="20px" />
    </uni-link>

    <navigator icon-btn url="/pages/about" title="About">
      <Icon icon="carbon:dicom-overlay" width="20px" />
    </navigator>
  </view>
</template>
